/*
CDOC
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 *** Function:	zgtmsg_(prmt,msg,prmtlen,msglen)		D. Trimmer
 
 *** Purpose:	Prints a prompt message on the standard output, and
		receives a reply on the standard intput.
 
 *** Inputs:	prmt	A pointer to a string containing the prompt.
			The end of prompt delimeter is a '$'.
		msg	A pointer to a string to receive the prompt.
		prmtlen A int containing the size of prmt (automatically
			generated by UNIX VAX F77)
		msglen  A int containing the size of msg (automatically
			generated by UNIX VAX F77)
 
 *** Returns:	message from standard input is returned in msg
 
 *** Notes:	This function is to be called by a FORTRAN routine.  The
		'_' is appended to the name for compatibility with FORTRAN.
 
		Arguments prmtlen and msglen are for generated by F77.
 
 *** Calls:	Function getline()
 
 *** History:	07/24/84   Copied from zgtmsg_()--D. Trimmer
		07/24/84   Tested--D. Trimmer
 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
CEND
*/
 
#include "stdu.h"
 
int getlineSAC(FILE* pfd, char* pch, short maxlen);

void zgtmsg(prmt,prmtlen,msg,msglen)
char *prmt;		/* pointer to prompt message */
int prmtlen;		/* length of prmt array */
char *msg;		/* pointer to character array to receive input */
int msglen;		/* length of msg array */
 
{
 
	while (*prmt != '$')
		putchar (*(prmt++));	/* print prompt */
	putchar('\n');
 
	getlineSAC (stdin,msg,(short) msglen);
	return;
}
 
 
 
