/*
CDOC
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 *** Function:	zwprmt_(prmt,pnumc,prmtlen)			D. Trimmer
 
 *** Purpose:	Prints a prompt message on the standard output, without a
		carriage return
 
 *** Inputs:	prmt	A pointer to a string containing the prompt.
			The end of prompt delimeter is a '$'.
		pnumc	A pointer to the number of charcters in prompt.
		prmtlen A int containing the size of prmt (automatically
			generated by UNIX VAX F77)
 
 *** Returns:	none
 
 *** Notes:	This function is to be called by a FORTRAN routine.  The
		'_' is appended to the name for compatibility with FORTRAN.
 
		Arguments prmtlen and msglen are for compatibility with F77.
		
 *** History:	07/24/84   Under development--D. Trimmer
		07/24/84   Tested--D. Trimmer
                04/10/85   Flush stdout after writing
 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
CEND
*/
 
#include "stdu.h"
 

void zwprmt(prmt,prmtlen,pnumc)
char *prmt;		/* pointer to prompt message */
int prmtlen;		/* length of prmt array */
int pnumc;		/* pointer to number of characters in prompt */
 
{
	int i;		/* index */
 
	for (i=0;i<pnumc;++i)
		putchar(*(prmt++));	/* type prompt */
        fflush(stdout);
 
	return;
}
 
 
